#!/bin/bash 
git rm --cached ./config/Configuration.pyc
git rm --cached ./config/__init__.pyc
git rm --cached ./lib/interaction/EventManager.pyc
git rm --cached ./lib/interaction/__init__.pyc
git rm --cached ./lib/ground/connector/__init__.pyc
git rm --cached ./lib/ground/connector/Mover.pyc
git rm --cached ./lib/ground/__init__.pyc
git rm --cached ./lib/simulation/SimulationManager.pyc
git rm --cached ./lib/simulation/TermitesSimulator.pyc
git rm --cached ./lib/simulation/__init__.pyc
git rm --cached ./lib/Core.pyc
git rm --cached ./lib/entity/ObjectAlive.pyc
git rm --cached ./lib/entity/Object.pyc
git rm --cached ./lib/entity/__init__.pyc
git rm --cached ./lib/entity/bug/Bug.pyc
git rm --cached ./lib/entity/bug/__init__.pyc
git rm --cached ./lib/entity/bug/termite/Termite.pyc
git rm --cached ./lib/entity/bug/termite/__init__.pyc
git rm --cached ./lib/entity/bug/termite/Worker.pyc
git rm --cached ./lib/__init__.pyc
git rm --cached ./lib/actions/Wait.pyc
git rm --cached ./lib/actions/__init__.pyc
git rm --cached ./lib/actions/Move/Termite.pyc
git rm --cached ./lib/actions/Move/Move.pyc
git rm --cached ./lib/actions/Move/__init__.pyc
git rm --cached ./lib/brain/ObjectAlive.pyc
git rm --cached ./lib/brain/Brain.pyc
git rm --cached ./lib/brain/__init__.pyc
git rm --cached ./lib/brain/bug/Bug.pyc
git rm --cached ./lib/brain/bug/__init__.pyc
git rm --cached ./lib/brain/bug/termite/Termite.pyc
git rm --cached ./lib/brain/bug/termite/__init__.pyc
git rm --cached ./lib/brain/bug/termite/Worker.pyc
git rm --cached ./lib/Pygame.pyc
git rm --cached ./config/Configuration.pyc
git rm --cached ./config/__init__.pyc
git rm --cached ./lib/interaction/EventManager.pyc
git rm --cached ./lib/interaction/__init__.pyc
git rm --cached ./lib/ground/connector/__init__.pyc
git rm --cached ./lib/ground/connector/Mover.pyc
git rm --cached ./lib/ground/__init__.pyc
git rm --cached ./lib/simulation/SimulationManager.pyc
git rm --cached ./lib/simulation/TermitesSimulator.pyc
git rm --cached ./lib/simulation/__init__.pyc
git rm --cached ./lib/Core.pyc
git rm --cached ./lib/entity/ObjectAlive.pyc
git rm --cached ./lib/entity/Object.pyc
git rm --cached ./lib/entity/__init__.pyc
git rm --cached ./lib/entity/bug/Bug.pyc
git rm --cached ./lib/entity/bug/__init__.pyc
git rm --cached ./lib/entity/bug/termite/Termite.pyc
git rm --cached ./lib/entity/bug/termite/__init__.pyc
git rm --cached ./lib/entity/bug/termite/Worker.pyc
git rm --cached ./lib/__init__.pyc
git rm --cached ./lib/actions/Wait.pyc
git rm --cached ./lib/actions/__init__.pyc
git rm --cached ./lib/actions/Move/Termite.pyc
git rm --cached ./lib/actions/Move/Move.pyc
git rm --cached ./lib/actions/Move/__init__.pyc
git rm --cached ./lib/brain/ObjectAlive.pyc
git rm --cached ./lib/brain/Brain.pyc
git rm --cached ./lib/brain/__init__.pyc
git rm --cached ./lib/brain/bug/Bug.pyc
git rm --cached ./lib/brain/bug/__init__.pyc
git rm --cached ./lib/brain/bug/termite/Termite.pyc
git rm --cached ./lib/brain/bug/termite/__init__.pyc
git rm --cached ./lib/brain/bug/termite/Worker.pyc
git rm --cached ./lib/Pygame.pyc
